import { chmodSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { afterEach, describe, expect, it } from "vitest";

const ROOT = join(import.meta.dirname, "..");
const SCRIPT =
  process.env.KSPEC_RELEASE_VALIDATION_SCRIPT ?? join(ROOT, "scripts", "validate-release.sh");
const dirs: string[] = [];
const COMMIT_A = "a".repeat(40);
const COMMIT_B = "b".repeat(40);

function fakeBoundary(name: string, body: string): string {
  const dir = dirs.at(-1)!;
  const path = join(dir, name);
  writeFileSync(path, `#!/usr/bin/env bash\nset -euo pipefail\n${body}\n`);
  chmodSync(path, 0o755);
  return path;
}

function run(
  mode: "resolve" | "verify",
  overrides: Record<string, string> = {},
): ReturnType<typeof spawnSync> {
  const dir = mkdtempSync(join(tmpdir(), "kspec-release-validation-"));
  dirs.push(dir);
  fakeBoundary(
    "git",
    `case "$1" in
  rev-parse)
    case "$2" in
      HEAD) printf '%s\\n' "\${FAKE_HEAD}" ;;
      refs/tags/*) printf '%s\\n' "\${FAKE_TAG_COMMIT}" ;;
      *) printf '%s\\n' "\${FAKE_EVENT_COMMIT}" ;;
    esac ;;
  ls-remote)
    if [[ "\${FAKE_REMOTE_KIND}" == annotated ]]; then
      printf '%s\\trefs/tags/%s\\n' "\${FAKE_TAG_OBJECT}" "\${RELEASE_TAG}"
      printf '%s\\trefs/tags/%s^{}\\n' "\${FAKE_REMOTE_COMMIT}" "\${RELEASE_TAG}"
    elif [[ "\${FAKE_REMOTE_KIND}" == lightweight ]]; then
      printf '%s\\trefs/tags/%s\\n' "\${FAKE_REMOTE_COMMIT}" "\${RELEASE_TAG}"
    fi ;;
  *) exit 91 ;;
esac`,
  );
  fakeBoundary(
    "gh",
    `[[ "\${FAKE_GH_FAIL:-0}" == 0 ]] || exit "\${FAKE_GH_FAIL}"
printf '%b\\n' "\${FAKE_GH_OUTPUT}"`,
  );
  fakeBoundary(
    "node",
    `if [[ "$*" == *package-lock* ]]; then printf '%s\\n' "\${FAKE_LOCK_VERSION}"; else printf '%s\\n' "\${FAKE_PACKAGE_VERSION}"; fi`,
  );

  const output = join(dir, "github-output");
  return spawnSync("bash", [SCRIPT, mode], {
    cwd: ROOT,
    encoding: "utf8",
    env: {
      ...process.env,
      PATH: `${dir}:${process.env.PATH}`,
      GITHUB_OUTPUT: output,
      GITHUB_REPOSITORY: "kynetic/spec",
      EVENT_NAME: "release",
      RELEASE_TAG: "v1.2.3",
      RELEASE_EVENT_COMMIT: COMMIT_A,
      EXPECTED_COMMIT: COMMIT_A,
      FAKE_HEAD: COMMIT_A,
      FAKE_TAG_COMMIT: COMMIT_A,
      FAKE_EVENT_COMMIT: COMMIT_A,
      FAKE_REMOTE_COMMIT: COMMIT_A,
      FAKE_REMOTE_KIND: "lightweight",
      FAKE_TAG_OBJECT: "c".repeat(40),
      FAKE_PACKAGE_VERSION: "1.2.3",
      FAKE_LOCK_VERSION: "1.2.3",
      FAKE_GH_OUTPUT: "v1.2.3\\tfalse\\t2026-07-19T00:00:00Z",
      FAKE_GH_FAIL: "0",
      ...overrides,
    },
  });
}

afterEach(() => {
  for (const dir of dirs) rmSync(dir, { recursive: true, force: true });
  dirs.length = 0;
});

describe("release validation executable", () => {
  it("resolves a release event to its event commit and serializes stable outputs", () => {
    const result = run("resolve");
    expect(result.status, result.stderr).toBe(0);
    const outputPath = join(dirs.at(-1)!, "github-output");
    // eslint-disable-next-line no-source-scanning/no-source-file-reads -- Reads output generated by this test invocation.
    expect(readFileSync(outputPath, "utf8")).toBe(
      `tag=v1.2.3\ncommit=${COMMIT_A}\nversion=1.2.3\n`,
    );
  });

  it("resolves a published non-draft manual release from the tag commit", () => {
    const result = run("resolve", {
      EVENT_NAME: "workflow_dispatch",
      RELEASE_EVENT_COMMIT: "",
    });
    expect(result.status, result.stderr).toBe(0);
  });

  it.each([
    ["invalid tag", { RELEASE_TAG: "release-1.2.3" }],
    ["package mismatch", { FAKE_PACKAGE_VERSION: "1.2.4" }],
    ["lock mismatch", { FAKE_LOCK_VERSION: "1.2.4" }],
    ["release event mismatch", { FAKE_TAG_COMMIT: COMMIT_B }],
    [
      "draft manual release",
      { EVENT_NAME: "workflow_dispatch", FAKE_GH_OUTPUT: "v1.2.3\\ttrue\\t2026-07-19T00:00:00Z" },
    ],
    [
      "unpublished manual release",
      { EVENT_NAME: "workflow_dispatch", FAKE_GH_OUTPUT: "v1.2.3\\tfalse\\t" },
    ],
    ["manual API failure", { EVENT_NAME: "workflow_dispatch", FAKE_GH_FAIL: "22" }],
  ])("fails closed for %s", (_name, env) => {
    expect(run("resolve", env).status).not.toBe(0);
  });

  it.each(["lightweight", "annotated"])("accepts a remotely bound %s tag", (kind) => {
    const result = run("verify", { FAKE_REMOTE_KIND: kind });
    expect(result.status, result.stderr).toBe(0);
  });

  it("rejects a moved remote tag while remaining on the authoritative checkout", () => {
    const result = run("verify", { FAKE_REMOTE_COMMIT: COMMIT_B });
    expect(result.status).not.toBe(0);
    expect(result.stderr).toContain("no longer resolves to authoritative commit");
  });

  it("rejects a checkout mismatch even when the tag and checkout match each other", () => {
    const result = run("verify", {
      FAKE_HEAD: COMMIT_B,
      FAKE_REMOTE_COMMIT: COMMIT_B,
    });
    expect(result.status).not.toBe(0);
    expect(result.stderr).toContain("does not match authoritative commit");
  });
});
