import * as fs from "node:fs/promises";
import * as path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { stringify as toYaml } from "yaml";
import {
  cleanupTempDir,
  createTempDir,
  initGitRepo,
  kspec,
  kspecJson,
  testUlid,
  testUlids,
} from "./helpers/cli.js";

/**
 * Helper: set up a split storage environment in a temp directory.
 * Creates the necessary directory structure for per-task storage.
 * Returns the env overrides needed for CLI commands.
 */
async function setupSplitEnv(
  tempDir: string,
): Promise<{ env: Record<string, string> }> {
  initGitRepo(tempDir);

  const specDir = path.join(tempDir, ".kspec");
  await fs.mkdir(specDir, { recursive: true });

  // Write minimal manifest
  await fs.writeFile(
    path.join(specDir, "kynetic.yaml"),
    toYaml({ kynetic_spec: "1.0", title: "Test Project" }),
  );

  // Create tasks directory
  await fs.mkdir(path.join(specDir, "tasks"), { recursive: true });

  // Write an empty index file
  await fs.writeFile(
    path.join(specDir, "project.tasks.yaml"),
    toYaml([]),
  );

  return { env: { KSPEC_SPEC_DIR: specDir } };
}

/**
 * Helper: create a per-task directory with task.yaml and notes.yaml.
 */
async function createTaskDir(
  tempDir: string,
  ulid: string,
  slug: string,
  overrides: Record<string, unknown> = {},
): Promise<void> {
  const taskDir = path.join(tempDir, ".kspec", "tasks", ulid);
  await fs.mkdir(taskDir, { recursive: true });

  const coreData = {
    _ulid: ulid,
    slugs: [slug],
    title: `Task ${slug}`,
    type: "task",
    status: "pending",
    priority: 3,
    tags: ["test"],
    depends_on: [],
    blocked_by: [],
    created_at: "2026-03-20T00:00:00.000Z",
    todos: [],
    ...overrides,
  };

  await fs.writeFile(path.join(taskDir, "task.yaml"), toYaml(coreData));

  await fs.writeFile(
    path.join(taskDir, "notes.yaml"),
    toYaml({ notes: [] }),
  );
}

/**
 * Helper: add an entry to the index file.
 */
async function addToIndex(
  tempDir: string,
  ulid: string,
  slug: string,
  overrides: Record<string, unknown> = {},
): Promise<void> {
  const indexPath = path.join(tempDir, ".kspec", "project.tasks.yaml");
  const { parse } = await import("yaml");
  const content = await fs.readFile(indexPath, "utf-8");
  const existing = parse(content) || [];
  const entries = Array.isArray(existing) ? existing : [];

  entries.push({
    _ulid: ulid,
    slugs: [slug],
    title: `Task ${slug}`,
    type: "task",
    status: "pending",
    priority: 3,
    tags: ["test"],
    depends_on: [],
    blocked_by: [],
    created_at: "2026-03-20T00:00:00.000Z",
    notes_count: 0,
    todos_count: 0,
    ...overrides,
  });

  await fs.writeFile(indexPath, toYaml(entries));
}

describe("kspec task rebuild-index", () => {
  let tempDir: string;
  let env: Record<string, string>;

  beforeEach(async () => {
    tempDir = await createTempDir("kspec-rebuild-index-");
  });

  afterEach(async () => {
    if (tempDir) {
      await cleanupTempDir(tempDir);
    }
  });

  // ── AC: @task-index-rebuild ac-1 ──────────────────────────────────────────
  // Given: Per-task directories exist
  // When: An index rebuild is requested
  // Then: The index file is regenerated by scanning all task directories
  //       and extracting indexed fields

  // AC: @task-index-rebuild ac-1
  it("scans per-task directories and rebuilds index entries", async () => {
    ({ env } = await setupSplitEnv(tempDir));
    const [id1, id2] = testUlids("RBD", 2);
    await createTaskDir(tempDir, id1, "task-alpha");
    await createTaskDir(tempDir, id2, "task-beta");
    // Index is empty — rebuild should find 2 tasks
    const result = kspec("task rebuild-index --repair --force", tempDir, { env });
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("2");
    expect(result.stdout).toContain("rebuilt");

    // Verify the index now contains both tasks
    const indexContent = await fs.readFile(
      path.join(tempDir, ".kspec", "project.tasks.yaml"),
      "utf-8",
    );
    expect(indexContent).toContain(id1);
    expect(indexContent).toContain(id2);
  });

  // ── AC: @task-index-rebuild ac-2 ──────────────────────────────────────────
  // Given: The rebuilt index differs from the current index
  // When: The rebuild completes
  // Then: The differences are reported to the user

  // AC: @task-index-rebuild ac-2
  it("reports differences between current and rebuilt index", async () => {
    ({ env } = await setupSplitEnv(tempDir));
    const [id1, id2] = testUlids("DFFRPT", 2);
    await createTaskDir(tempDir, id1, "task-same");
    await addToIndex(tempDir, id1, "task-same");

    // Create a second task dir but don't add to index (will be "added")
    await createTaskDir(tempDir, id2, "task-new");

    const result = kspec("task rebuild-index", tempDir, { env });
    expect(result.exitCode).toBe(0);
    // Should report the added task
    expect(result.stdout).toContain("Added");
    expect(result.stdout).toContain("task-new");
    expect(result.stdout).toContain("difference");
  });

  // AC: @task-index-rebuild ac-2
  it("reports changed fields when index entry differs from per-task data", async () => {
    ({ env } = await setupSplitEnv(tempDir));
    const id = testUlid("CHNG");
    // Per-task dir has priority 1
    await createTaskDir(tempDir, id, "task-changed", { priority: 1 });
    // Index has priority 3 (default)
    await addToIndex(tempDir, id, "task-changed", { priority: 3 });

    const result = kspec("task rebuild-index", tempDir, { env });
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("Changed");
    expect(result.stdout).toContain("priority");
  });

  // AC: @task-index-rebuild ac-2
  it("reports removed entries (in index but not in per-task dirs)", async () => {
    ({ env } = await setupSplitEnv(tempDir));
    const [id1, id2] = testUlids("RMVD", 2);
    await createTaskDir(tempDir, id1, "task-exists");
    await addToIndex(tempDir, id1, "task-exists");
    // id2 is only in the index, not in per-task dirs
    await addToIndex(tempDir, id2, "task-stale");

    const result = kspec("task rebuild-index", tempDir, { env });
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("Removed");
    expect(result.stdout).toContain("task-stale");
  });

  // AC: @task-index-rebuild ac-2
  it("reports no differences when index matches per-task data", async () => {
    ({ env } = await setupSplitEnv(tempDir));
    const id = testUlid("SYNC");
    await createTaskDir(tempDir, id, "task-synced");
    await addToIndex(tempDir, id, "task-synced");

    const result = kspec("task rebuild-index", tempDir, { env });
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("up to date");
  });

  // ── AC: @task-index-rebuild ac-3 ──────────────────────────────────────────
  // Given: The rebuild is run in repair mode
  // When: Differences are found
  // Then: The index is overwritten with the rebuilt version

  // AC: @task-index-rebuild ac-3
  it("overwrites index with rebuilt version in repair mode", async () => {
    ({ env } = await setupSplitEnv(tempDir));
    const [id1, id2] = testUlids("REPR", 2);
    await createTaskDir(tempDir, id1, "task-keep");
    await createTaskDir(tempDir, id2, "task-add-me");
    // Only id1 in the index
    await addToIndex(tempDir, id1, "task-keep");

    const result = kspec("task rebuild-index --repair --force", tempDir, { env });
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("rebuilt");

    // Verify index now has both entries
    const indexContent = await fs.readFile(
      path.join(tempDir, ".kspec", "project.tasks.yaml"),
      "utf-8",
    );
    expect(indexContent).toContain(id1);
    expect(indexContent).toContain(id2);
  });

  // AC: @task-index-rebuild ac-3
  it("does not modify index without --repair flag", async () => {
    ({ env } = await setupSplitEnv(tempDir));
    const id = testUlid("NRPR");
    await createTaskDir(tempDir, id, "task-unreported");
    // Index is empty — should report diff but not change index

    const result = kspec("task rebuild-index", tempDir, { env });
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("--repair");

    // Index should still be empty
    const indexContent = await fs.readFile(
      path.join(tempDir, ".kspec", "project.tasks.yaml"),
      "utf-8",
    );
    expect(indexContent).not.toContain(id);
  });

  // ── AC: @task-index-rebuild ac-4 ──────────────────────────────────────────
  // Given: No per-task directories exist
  // When: An index rebuild is requested
  // Then: The command reports that no task directories were found and
  //       suggests running migration first

  // AC: @task-index-rebuild ac-4
  it("reports error when no per-task directories exist", async () => {
    ({ env } = await setupSplitEnv(tempDir));
    // No task directories created — empty tasks/ dir

    const result = kspec("task rebuild-index", tempDir, {
      expectFail: true,
      env,
    });
    expect(result.exitCode).not.toBe(0);
    const output = result.stderr || result.stdout;
    expect(output).toContain("No per-task directories found");
    expect(output).toContain("migrate");
  });

  // ── AC: @trait-dry-run ac-1 ───────────────────────────────────────────────
  // Given: command supports dry run
  // When: --dry-run flag is provided
  // Then: show what would be changed without applying

  // AC: @trait-dry-run ac-1
  it("supports --dry-run flag to preview changes", async () => {
    ({ env } = await setupSplitEnv(tempDir));
    const id = testUlid("DRYP");
    await createTaskDir(tempDir, id, "task-dry-preview");
    // Empty index — would add entry

    const result = kspec("task rebuild-index --dry-run", tempDir, { env });
    expect(result.exitCode).toBe(0);
    const combined = result.stdout + " " + result.stderr;
    expect(combined).toMatch(/DRY RUN/i);
    expect(combined).toContain("Added");
    expect(combined).toContain("task-dry-preview");
  });

  // ── AC: @trait-dry-run ac-2 ───────────────────────────────────────────────
  // Given: dry run mode is active
  // When: command completes
  // Then: no files are modified

  // AC: @trait-dry-run ac-2
  it("does not modify files in dry-run mode", async () => {
    ({ env } = await setupSplitEnv(tempDir));
    const id = testUlid("DRYN");
    await createTaskDir(tempDir, id, "task-dry-nomod");
    const indexPath = path.join(tempDir, ".kspec", "project.tasks.yaml");
    const indexBefore = await fs.readFile(indexPath, "utf-8");

    kspec("task rebuild-index --dry-run", tempDir, { env });

    const indexAfter = await fs.readFile(indexPath, "utf-8");
    expect(indexAfter).toBe(indexBefore);
  });

  // ── AC: @trait-dry-run ac-3 ───────────────────────────────────────────────
  // Given: dry run mode is active
  // When: output is shown
  // Then: clear indication that this is a preview

  // AC: @trait-dry-run ac-3
  it("shows clear DRY RUN indication in output", async () => {
    ({ env } = await setupSplitEnv(tempDir));
    const id = testUlid("DRYM");
    await createTaskDir(tempDir, id, "task-dry-msg");

    const result = kspec("task rebuild-index --dry-run", tempDir, { env });
    expect(result.exitCode).toBe(0);
    expect(result.stdout + " " + result.stderr).toMatch(/DRY RUN/i);
  });

  // AC: @trait-dry-run ac-3
  it("shows DRY RUN indication even when index is already synced", async () => {
    ({ env } = await setupSplitEnv(tempDir));
    const id = testUlid("DRYS");
    await createTaskDir(tempDir, id, "task-dry-synced");
    await addToIndex(tempDir, id, "task-dry-synced");

    const result = kspec("task rebuild-index --dry-run", tempDir, { env });
    expect(result.exitCode).toBe(0);
    expect(result.stdout + " " + result.stderr).toMatch(/DRY RUN/i);
    expect(result.stdout).toContain("up to date");
  });

  // ── AC: @trait-dry-run ac-4 ───────────────────────────────────────────────
  // Given: dry run mode is active
  // When: command would error
  // Then: error shown but no state changed

  // AC: @trait-dry-run ac-4
  it("shows error in dry-run mode without changing state", async () => {
    ({ env } = await setupSplitEnv(tempDir));
    // No task dirs — would error
    const indexPath = path.join(tempDir, ".kspec", "project.tasks.yaml");
    const indexBefore = await fs.readFile(indexPath, "utf-8");

    const result = kspec("task rebuild-index --dry-run", tempDir, {
      expectFail: true,
      env,
    });
    // Should still show the error
    const output = result.stderr || result.stdout;
    expect(output).toContain("No per-task directories found");

    // Index unchanged
    const indexAfter = await fs.readFile(indexPath, "utf-8");
    expect(indexAfter).toBe(indexBefore);
  });

  // ── AC: @trait-dry-run ac-5 ───────────────────────────────────────────────
  // Given: --dry-run and --force both provided
  // When: command executes
  // Then: dry run takes precedence (no changes made)

  // AC: @trait-dry-run ac-5
  it("dry-run takes precedence over --force --repair", async () => {
    ({ env } = await setupSplitEnv(tempDir));
    const id = testUlid("DRYF");
    await createTaskDir(tempDir, id, "task-dry-force");
    const indexPath = path.join(tempDir, ".kspec", "project.tasks.yaml");
    const indexBefore = await fs.readFile(indexPath, "utf-8");

    const result = kspec("task rebuild-index --dry-run --repair --force", tempDir, {
      env,
    });
    expect(result.exitCode).toBe(0);
    expect(result.stdout + " " + result.stderr).toMatch(/DRY RUN/i);

    // Index should not have been modified
    const indexAfter = await fs.readFile(indexPath, "utf-8");
    expect(indexAfter).toBe(indexBefore);
  });

  // ── AC: @trait-dry-run ac-6 ───────────────────────────────────────────────
  // Given: dry run in JSON mode
  // When: --dry-run --json provided
  // Then: JSON output includes dry_run boolean field

  // AC: @trait-dry-run ac-6
  it("includes dry_run field in JSON output", async () => {
    ({ env } = await setupSplitEnv(tempDir));
    const id = testUlid("DRYJ");
    await createTaskDir(tempDir, id, "task-dry-json");

    const result = kspecJson<{
      dry_run: boolean;
      task_dirs_found: number;
      differences: unknown[];
    }>("task rebuild-index --dry-run", tempDir, { env });

    expect(result.dry_run).toBe(true);
    expect(result.task_dirs_found).toBeGreaterThan(0);
    expect(Array.isArray(result.differences)).toBe(true);
  });

  // ── AC: @trait-error-guidance ac-1 ────────────────────────────────────────
  // Given: command encounters error
  // When: error message is shown
  // Then: includes description of what went wrong

  // AC: @trait-error-guidance ac-1
  it("error includes description of what went wrong", async () => {
    ({ env } = await setupSplitEnv(tempDir));
    const result = kspec("task rebuild-index", tempDir, {
      expectFail: true,
      env,
    });
    const output = result.stderr || result.stdout;
    expect(output).toContain("No per-task directories found");
  });

  // ── AC: @trait-error-guidance ac-2 ────────────────────────────────────────
  // Given: command encounters error
  // When: error message is shown
  // Then: includes suggested action to resolve

  // AC: @trait-error-guidance ac-2
  it("error includes suggested action to resolve", async () => {
    ({ env } = await setupSplitEnv(tempDir));
    const result = kspec("task rebuild-index", tempDir, {
      expectFail: true,
      env,
    });
    const output = result.stderr || result.stdout;
    expect(output).toContain("migrate");
  });

  // ── AC: @trait-error-guidance ac-6 ────────────────────────────────────────
  // Given: error in JSON mode
  // When: --json is active
  // Then: guidance included in structured error object

  // AC: @trait-error-guidance ac-6
  it("error in JSON mode includes guidance", async () => {
    ({ env } = await setupSplitEnv(tempDir));
    const result = kspec("task rebuild-index --json", tempDir, {
      expectFail: true,
      env,
    });
    // JSON error should be in stderr
    const errorOutput = result.stderr;
    expect(errorOutput).toBeTruthy();
    const parsed = JSON.parse(errorOutput);
    expect(parsed.success).toBe(false);
    expect(parsed.error).toBeTruthy();
  });

  // ── JSON output ───────────────────────────────────────────────────────────

  it("returns structured JSON with differences", async () => {
    ({ env } = await setupSplitEnv(tempDir));
    const [id1, id2] = testUlids("JSNDF", 2);
    await createTaskDir(tempDir, id1, "task-json-same");
    await addToIndex(tempDir, id1, "task-json-same");
    await createTaskDir(tempDir, id2, "task-json-new");

    const result = kspecJson<{
      task_dirs_found: number;
      index_entries_current: number;
      index_entries_rebuilt: number;
      differences: Array<{ type: string; ulid: string; title?: string }>;
      repaired: boolean;
    }>("task rebuild-index", tempDir, { env });

    expect(result.task_dirs_found).toBe(2);
    expect(result.index_entries_current).toBe(1);
    expect(result.index_entries_rebuilt).toBe(2);
    expect(result.differences).toHaveLength(1);
    expect(result.differences[0].type).toBe("added");
    expect(result.differences[0].ulid).toBe(id2);
    expect(result.repaired).toBe(false);
  });

  it("JSON repair mode sets repaired to true", async () => {
    ({ env } = await setupSplitEnv(tempDir));
    const id = testUlid("JSNRP");
    await createTaskDir(tempDir, id, "task-json-repair");

    const result = kspecJson<{
      repaired: boolean;
      differences: unknown[];
    }>("task rebuild-index --repair --force", tempDir, { env });

    expect(result.repaired).toBe(true);
    expect(result.differences.length).toBeGreaterThan(0);
  });
});
