/**
 * Docs content bundled at build time via the vite-plugin-docs virtual module.
 *
 * Each entry maps a URL slug (e.g. "getting-started" or "history/KYNETIC_SPEC_DESIGN")
 * to its raw markdown source. The manifest is generated by scanning the repository's
 * top-level docs/ directory at build time so that no runtime file reads or network
 * requests are needed — content works identically in daemon mode, static mode, and
 * when offline.
 */

export interface DocsEntry {
	/** URL-safe slug derived from the file path (without .md extension) */
	slug: string;
	/** Human-readable title extracted from the first H1, or derived from filename */
	title: string;
	/** Raw markdown source */
	content: string;
	/** Original relative path from docs/ (e.g. "getting-started.md") */
	path: string;
}

export interface DocsManifest {
	entries: DocsEntry[];
}

// Import the build-time generated manifest
// @ts-expect-error — virtual module provided by vite-plugin-docs
import manifest from 'virtual:docs';

export const docsManifest: DocsManifest = manifest;

/**
 * Look up a docs entry by its URL slug.
 */
export function getDocsEntry(slug: string): DocsEntry | undefined {
	return docsManifest.entries.find((e) => e.slug === slug);
}

/**
 * Get the docs landing page (first entry, or a specific index if present).
 */
export function getDocsLandingEntry(): DocsEntry | undefined {
	// Prefer an explicit index page if one exists
	return docsManifest.entries.find((e) => e.slug === 'index') ?? docsManifest.entries[0];
}

/**
 * Get all entries for building navigation.
 */
export function getDocsEntries(): DocsEntry[] {
	return docsManifest.entries;
}
