_ulid: 01KNBS17JCVH7DPTJJNE3K5GCA
slugs:
  - task-fix-session-dir-fd-leak
title: Close directory handles deterministically during session directory enumeration
type: task
description: "-"
spec_ref: "@daemon-entity-cache"
meta_ref: null
plan_ref: null
status: pending_review
blocked_by: []
depends_on: []
context: []
priority: 1
tags:
  - daemon
  - sessions
  - bug
vcs_refs: []
review_ref: "@01KNBSKXGGHAPTZG7JGED988J7"
submission_linkage:
  review_url: null
  branch: dev
  captured_at: 2026-04-04T08:24:12.175Z
  commit: d51b5485e0c0f3dc3a03e65d05524397937c0075
  remote: origin
  remote_url: git@github.com:lepahc/kynetic-spec.git
  upstream_ref: refs/heads/dev
session_id: 01KNBS2KSAR3A2GN1R1WBGN7BQ
history:
  - author: Jacob Chapel
    changes:
      status:
        new: in_progress
        previous: pending
      session_id:
        new: 01KNBS2KSAR3A2GN1R1WBGN7BQ
        previous: null
      started_at:
        new: 2026-04-04T08:17:41.818Z
        previous: null
    command: task-start
    timestamp: 2026-04-04T08:17:41.818Z
  - author: Jacob Chapel
    changes:
      status:
        new: pending_review
        previous: in_progress
      submission_linkage:
        new:
          review_url: null
          branch: dev
          captured_at: 2026-04-04T08:24:12.175Z
          commit: d51b5485e0c0f3dc3a03e65d05524397937c0075
          remote: origin
          remote_url: git@github.com:lepahc/kynetic-spec.git
          upstream_ref: refs/heads/dev
        previous: null
      submitted_at:
        new: 2026-04-04T08:24:12.179Z
        previous: null
    command: task-submit
    timestamp: 2026-04-04T08:24:12.180Z
  - author: Jacob Chapel
    changes:
      review_ref:
        new: "@01KNBSKXGGHAPTZG7JGED988J7"
        previous: null
    command: review-link
    timestamp: 2026-04-04T08:26:43.547Z
created_at: 2026-04-04T08:16:28.748Z
started_at: 2026-04-04T08:17:41.818Z
submitted_at: 2026-04-04T08:24:12.179Z
todos: []
automation: eligible
