/**
 * Agent instruction generation commands.
 *
 * AC: @agent-instruction-gen ac-1 - kspec agents generate creates kspec-agents.md in project root
 * AC: @agent-instruction-gen ac-2 - output includes Finding Information table with row per skill
 * AC: @agent-instruction-gen ac-3 - output includes conventions section listing rules by domain
 * AC: @agent-instruction-gen ac-4 - output contains freshness comment with kspec version and timestamp
 * AC: @agent-instruction-gen ac-5 - kspec agents status reports stale when not regenerated after meta changes
 */

import * as crypto from "node:crypto";
import * as fs from "node:fs/promises";
import { createRequire } from "node:module";
import * as path from "node:path";
import chalk from "chalk";
import type { Command } from "commander";
import {
  initContext,
  loadMetaContext,
  type LoadedConvention,
  type LoadedSkill,
  type LoadedWorkflow,
} from "../../parser/index.js";
import { errors } from "../../strings/errors.js";
import { EXIT_CODES } from "../exit-codes.js";
import { error, output, success } from "../output.js";

// Read version from package.json at runtime
const require = createRequire(import.meta.url);
const { version } = require("../../../package.json");

/**
 * File name for generated agent instructions
 */
const GENERATED_FILE_NAME = "kspec-agents.md";

/**
 * Hash file name for tracking freshness
 */
const HASH_FILE_NAME = ".kspec-agents-hash";

/**
 * Compute SHA256 hash of content
 */
function computeHash(content: string): string {
  return crypto.createHash("sha256").update(content, "utf-8").digest("hex");
}

/**
 * Generate a hash of the meta content that affects the generated file.
 * This is used to detect if the generated file is stale.
 */
function computeMetaHash(
  skills: LoadedSkill[],
  conventions: LoadedConvention[],
  workflows: LoadedWorkflow[],
): string {
  // Create a stable representation of the meta content
  const data = {
    skills: skills.map((s) => ({
      id: s.id,
      name: s.name,
      description: s.description,
    })),
    conventions: conventions.map((c) => ({
      domain: c.domain,
      rules: c.rules,
    })),
    workflows: workflows.map((w) => ({
      id: w.id,
      trigger: w.trigger,
      description: w.description,
    })),
  };
  return computeHash(JSON.stringify(data));
}

/**
 * Generate the Finding Information table for skills.
 * AC: @agent-instruction-gen ac-2 - Finding Information table with row per skill
 */
function generateSkillsTable(skills: LoadedSkill[]): string {
  if (skills.length === 0) {
    return "";
  }

  const lines: string[] = [
    "## Finding Information",
    "",
    "Use skills and CLI help for detailed documentation:",
    "",
    "| Need | Where to look |",
    "|------|---------------|",
  ];

  for (const skill of skills) {
    const description = skill.description || skill.name;
    // Use the skill ID as the reference (prefixed with /)
    lines.push(`| ${description} | \`/${skill.id}\` skill |`);
  }

  lines.push("");
  lines.push(
    "Skills inject their full documentation when invoked — you don't need to memorize their contents.",
  );
  lines.push("");

  return lines.join("\n");
}

/**
 * Generate the conventions section.
 * AC: @agent-instruction-gen ac-3 - conventions section listing rules by domain
 */
function generateConventionsSection(conventions: LoadedConvention[]): string {
  if (conventions.length === 0) {
    return "";
  }

  const lines: string[] = ["## Conventions", ""];

  for (const convention of conventions) {
    lines.push(`### ${convention.domain}`);
    lines.push("");

    for (const rule of convention.rules) {
      lines.push(`- ${rule}`);
    }

    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Generate the workflows summary section.
 */
function generateWorkflowsSection(workflows: LoadedWorkflow[]): string {
  if (workflows.length === 0) {
    return "";
  }

  const lines: string[] = [
    "## Workflows",
    "",
    "Available workflows:",
    "",
  ];

  for (const workflow of workflows) {
    const description = workflow.description || workflow.trigger;
    lines.push(`- **${workflow.id}**: ${description}`);
  }

  lines.push("");
  lines.push("Use `kspec workflow start @workflow-id` to start a workflow.");
  lines.push("");

  return lines.join("\n");
}

/**
 * Generate the freshness comment.
 * AC: @agent-instruction-gen ac-4 - freshness comment with kspec version and timestamp
 */
function generateFreshnessComment(timestamp: string): string {
  return `<!-- Generated by kspec v${version} at ${timestamp} -->\n<!-- Do not edit manually - regenerate with: kspec agents generate -->\n\n`;
}

/**
 * Generate the full kspec-agents.md content
 */
function generateAgentsContent(
  skills: LoadedSkill[],
  conventions: LoadedConvention[],
  workflows: LoadedWorkflow[],
  timestamp: string,
): string {
  const sections: string[] = [];

  // AC: @agent-instruction-gen ac-4 - freshness comment
  sections.push(generateFreshnessComment(timestamp));

  // Header
  sections.push("# kspec Agent Instructions\n");
  sections.push(
    "This file is auto-generated from kspec meta. Include it in your AGENTS.md or similar agent instruction file.\n\n",
  );

  // AC: @agent-instruction-gen ac-2 - Skills table
  const skillsTable = generateSkillsTable(skills);
  if (skillsTable) {
    sections.push(skillsTable);
  }

  // AC: @agent-instruction-gen ac-3 - Conventions section
  const conventionsSection = generateConventionsSection(conventions);
  if (conventionsSection) {
    sections.push(conventionsSection);
  }

  // Workflows summary
  const workflowsSection = generateWorkflowsSection(workflows);
  if (workflowsSection) {
    sections.push(workflowsSection);
  }

  return sections.join("");
}

/**
 * Result of checking agent file status
 */
interface AgentStatusResult {
  exists: boolean;
  path: string;
  status: "current" | "stale" | "missing";
  metaHash?: string;
  storedHash?: string;
  generatedAt?: string;
}

/**
 * Check the status of the generated agent file.
 * AC: @agent-instruction-gen ac-5 - reports stale when meta has changed
 */
async function checkAgentStatus(
  projectRoot: string,
  metaHash: string,
): Promise<AgentStatusResult> {
  const filePath = path.join(projectRoot, GENERATED_FILE_NAME);
  const hashPath = path.join(projectRoot, ".kspec", HASH_FILE_NAME);

  // Check if file exists
  try {
    await fs.access(filePath);
  } catch {
    return {
      exists: false,
      path: filePath,
      status: "missing",
      metaHash,
    };
  }

  // Check stored hash
  let storedHash: string | undefined;
  let generatedAt: string | undefined;

  try {
    const hashContent = await fs.readFile(hashPath, "utf-8");
    const hashData = JSON.parse(hashContent);
    storedHash = hashData.metaHash;
    generatedAt = hashData.generatedAt;
  } catch {
    // No hash file, treat as stale
    return {
      exists: true,
      path: filePath,
      status: "stale",
      metaHash,
    };
  }

  // Compare hashes
  const isCurrent = storedHash === metaHash;

  return {
    exists: true,
    path: filePath,
    status: isCurrent ? "current" : "stale",
    metaHash,
    storedHash,
    generatedAt,
  };
}

/**
 * Register agent instruction generation commands
 */
export function registerAgentsCommands(program: Command): void {
  const agents = program
    .command("agents")
    .description("Agent instruction generation commands");

  // AC: @agent-instruction-gen ac-1 - kspec agents generate
  // AC: @trait-dry-run ac-1 through ac-6 - dry-run support
  agents
    .command("generate")
    .description("Generate kspec-agents.md from meta (skills, conventions, workflows)")
    .option("--dry-run", "Show what would be generated without writing files")
    .action(async (options) => {
      try {
        const ctx = await initContext();

        if (!ctx.manifestPath) {
          error(errors.project.noKspecProject);
          process.exit(EXIT_CODES.ERROR);
        }

        const metaCtx = await loadMetaContext(ctx);
        const dryRun = options.dryRun || false;
        const timestamp = new Date().toISOString();

        // Generate content
        const content = generateAgentsContent(
          metaCtx.skills,
          metaCtx.conventions,
          metaCtx.workflows,
          timestamp,
        );

        // Compute meta hash for freshness tracking
        const metaHash = computeMetaHash(
          metaCtx.skills,
          metaCtx.conventions,
          metaCtx.workflows,
        );

        const outputPath = path.join(ctx.rootDir, GENERATED_FILE_NAME);
        const hashPath = path.join(ctx.rootDir, ".kspec", HASH_FILE_NAME);

        // AC: @trait-dry-run ac-3 - clear indication this is a preview
        if (dryRun) {
          output(
            {
              dry_run: true,
              path: outputPath,
              skills: metaCtx.skills.length,
              conventions: metaCtx.conventions.length,
              workflows: metaCtx.workflows.length,
              content,
            },
            () => {
              console.log(chalk.yellow("DRY RUN - No changes made"));
              console.log();
              console.log(chalk.gray(`Would write to: ${outputPath}`));
              console.log();
              console.log(chalk.gray("--- Generated content ---"));
              console.log(content);
              console.log(chalk.gray("--- End content ---"));
              console.log();
              console.log(
                chalk.yellow("No changes were made. Run without --dry-run to apply."),
              );
            },
          );
          return;
        }

        // AC: @trait-dry-run ac-2 - no files modified in dry run mode
        // Write the generated file
        await fs.writeFile(outputPath, content, "utf-8");

        // Write the hash file for freshness tracking
        await fs.mkdir(path.dirname(hashPath), { recursive: true });
        await fs.writeFile(
          hashPath,
          JSON.stringify(
            {
              metaHash,
              generatedAt: timestamp,
              version,
            },
            null,
            2,
          ),
          "utf-8",
        );

        output(
          {
            path: outputPath,
            skills: metaCtx.skills.length,
            conventions: metaCtx.conventions.length,
            workflows: metaCtx.workflows.length,
            generatedAt: timestamp,
          },
          () => {
            success(`Generated ${GENERATED_FILE_NAME}`, {
              skills: metaCtx.skills.length,
              conventions: metaCtx.conventions.length,
              workflows: metaCtx.workflows.length,
            });
            console.log(chalk.gray(`  Path: ${outputPath}`));
          },
        );
      } catch (err) {
        error("Failed to generate agent instructions", err);
        process.exit(EXIT_CODES.ERROR);
      }
    });

  // AC: @agent-instruction-gen ac-5 - kspec agents status
  agents
    .command("status")
    .description("Check if kspec-agents.md is up to date with meta")
    .action(async () => {
      try {
        const ctx = await initContext();

        if (!ctx.manifestPath) {
          error(errors.project.noKspecProject);
          process.exit(EXIT_CODES.ERROR);
        }

        const metaCtx = await loadMetaContext(ctx);

        // Compute current meta hash
        const metaHash = computeMetaHash(
          metaCtx.skills,
          metaCtx.conventions,
          metaCtx.workflows,
        );

        const status = await checkAgentStatus(ctx.rootDir, metaHash);

        output(status, () => {
          switch (status.status) {
            case "missing":
              console.log(chalk.yellow(`${GENERATED_FILE_NAME} does not exist`));
              console.log();
              console.log(
                chalk.gray("Run 'kspec agents generate' to create it."),
              );
              break;

            case "stale":
              console.log(
                chalk.yellow(`${GENERATED_FILE_NAME} is stale`),
              );
              console.log();
              console.log(
                chalk.gray(
                  "Meta has changed since the file was generated.",
                ),
              );
              console.log(
                chalk.gray("Run 'kspec agents generate' to regenerate."),
              );
              break;

            case "current":
              console.log(chalk.green(`${GENERATED_FILE_NAME} is up to date`));
              if (status.generatedAt) {
                console.log(chalk.gray(`  Generated: ${status.generatedAt}`));
              }
              break;
          }
        });
      } catch (err) {
        error("Failed to check agent status", err);
        process.exit(EXIT_CODES.ERROR);
      }
    });
}
