import { Command } from 'commander';
import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import * as readline from 'node:readline/promises';
import { success, error, info, warn } from '../output.js';

/**
 * Default manifest template
 */
function generateManifest(projectName: string, singleFile: boolean): string {
  const lines = [
    `# ${projectName} - Kynetic Spec`,
    `# Generated by kspec init`,
    ``,
    `kynetic: "1.0"`,
    ``,
    `project:`,
    `  name: "${projectName}"`,
    `  version: "0.1.0"`,
    `  status: draft`,
    `  description: |`,
    `    Add your project description here.`,
    ``,
  ];

  if (!singleFile) {
    lines.push(
      `# Module includes - add your spec modules here`,
      `includes:`,
      `  - modules/main.yaml`,
      ``,
    );
  }

  lines.push(
    `# Configuration`,
    `config:`,
    `  validation:`,
    `    strict_refs: true`,
    `    require_acceptance: false`,
    ``,
  );

  return lines.join('\n');
}

/**
 * Default module template
 */
function generateMainModule(projectName: string): string {
  return `# ${projectName} - Main Module
# Add your spec items here

items:
  - _ulid: # Generate with: node -e "const {ulid} = require('ulid'); console.log(ulid())"
    slugs: [example-feature]
    type: feature
    title: "Example Feature"
    description: |
      Describe your feature here.
    status:
      maturity: proposed
      implementation: not_started
`;
}

/**
 * Default tasks file template
 */
function generateTasksFile(projectName: string): string {
  return `# ${projectName} - Tasks
# Track implementation work here

tasks: []
`;
}

/**
 * Prompt user for input
 */
async function prompt(question: string, defaultValue?: string): Promise<string> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  try {
    const suffix = defaultValue ? ` (${defaultValue})` : '';
    const answer = await rl.question(`${question}${suffix}: `);
    return answer.trim() || defaultValue || '';
  } finally {
    rl.close();
  }
}

/**
 * Derive project name from directory
 */
function deriveProjectName(targetDir: string): string {
  const dirName = path.basename(path.resolve(targetDir));
  // Convert kebab-case or snake_case to Title Case
  return dirName
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

/**
 * Convert project name to slug (kebab-case)
 */
function toSlug(projectName: string): string {
  return projectName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

/**
 * Register the 'init' command
 */
export function registerInitCommand(program: Command): void {
  program
    .command('init [directory]')
    .description('Initialize a new kspec project')
    .option('-n, --name <name>', 'Project name')
    .option('--single-file', 'Create manifest only (no modules directory)')
    .option('--no-prompt', 'Skip interactive prompts, use defaults')
    .option('--force', 'Overwrite existing files')
    .action(async (directory, options) => {
      try {
        const targetDir = directory || process.cwd();
        const specDir = path.join(targetDir, 'spec');

        // Check if spec already exists
        try {
          await fs.access(specDir);
          if (!options.force) {
            error(`spec/ directory already exists in ${targetDir}`);
            console.log('Use --force to overwrite existing files');
            process.exit(1);
          }
          warn('Overwriting existing spec files');
        } catch {
          // Directory doesn't exist, good to proceed
        }

        // Determine project name
        let projectName = options.name;

        if (!projectName && options.prompt !== false) {
          const defaultName = deriveProjectName(targetDir);
          projectName = await prompt('Project name', defaultName);
        }

        if (!projectName) {
          projectName = deriveProjectName(targetDir);
        }

        const singleFile = options.singleFile || false;
        const slug = toSlug(projectName);

        info(`Initializing kspec project: ${projectName}`);

        // Create spec directory
        await fs.mkdir(specDir, { recursive: true });

        // Create manifest
        const manifestPath = path.join(specDir, `${slug}.yaml`);
        await fs.writeFile(manifestPath, generateManifest(projectName, singleFile), 'utf-8');
        console.log(`  Created ${path.relative(targetDir, manifestPath)}`);

        // Create tasks file
        const tasksPath = path.join(specDir, `${slug}.tasks.yaml`);
        await fs.writeFile(tasksPath, generateTasksFile(projectName), 'utf-8');
        console.log(`  Created ${path.relative(targetDir, tasksPath)}`);

        if (!singleFile) {
          // Create modules directory and main module
          const modulesDir = path.join(specDir, 'modules');
          await fs.mkdir(modulesDir, { recursive: true });

          const mainModulePath = path.join(modulesDir, 'main.yaml');
          await fs.writeFile(mainModulePath, generateMainModule(projectName), 'utf-8');
          console.log(`  Created ${path.relative(targetDir, mainModulePath)}`);
        }

        success(`Initialized kspec project in ${path.relative(process.cwd(), specDir) || 'spec/'}`, {
          projectName,
          specDir,
          singleFile,
        });

        console.log('\nNext steps:');
        console.log(`  1. Edit spec/${slug}.yaml to customize your project`);
        if (!singleFile) {
          console.log('  2. Add spec items to spec/modules/main.yaml');
        }
        console.log(`  ${singleFile ? '2' : '3'}. Run \`kspec tasks ready\` to see available tasks`);
      } catch (err) {
        error('Failed to initialize project', err);
        process.exit(1);
      }
    });
}
