import * as fs from "node:fs/promises";
import * as path from "node:path";
import * as readline from "node:readline/promises";
import type { Command } from "commander";
import { ulid } from "ulid";
import {
  getGitRoot,
  initializeShadow,
  isGitRepo,
  checkConfigMismatch,
  resolveProjectRoots,
  buildLinkedWorktreeMessage,
} from "../../parser/shadow.js";
import { loadProjectConfig } from "../../parser/config.js";
import { errors } from "../../strings/index.js";
import { EXIT_CODES } from "../exit-codes.js";
import { error, info, success, warn } from "../output.js";
import { runSetupPipeline } from "./setup.js";

/**
 * Default manifest template
 */
function generateManifest(
  projectName: string,
  singleFile: boolean,
  defaultModuleUlid?: string,
): string {
  const lines = [
    `# ${projectName} - Kynetic Spec`,
    `# Generated by kspec init`,
    ``,
    `kynetic: "1.2"`,
    ``,
    `project:`,
    `  name: "${projectName}"`,
    `  version: "0.1.0"`,
    `  status: draft`,
    `  description: |`,
    `    Add your project description here.`,
    ``,
    `task_storage:`,
    `  format: split`,
    ``,
    `plan_storage:`,
    `  format: folder`,
    ``,
    `review_storage:`,
    `  format: folder`,
    ``,
    `resource_storage:`,
    `  format: entity_scoped`,
    ``,
  ];

  if (!singleFile) {
    if (defaultModuleUlid) {
      lines.push(
        `# ULID of the default module created at init`,
        `default_module: "${defaultModuleUlid}"`,
        ``,
      );
    }
    lines.push(
      `# Module includes - add your spec modules here`,
      `includes:`,
      `  - modules/main.yaml`,
      ``,
    );
  }

  return lines.join("\n");
}

/**
 * Default module template as a referenceable module item.
 * Creates a real module with a ULID, slug, and type so that
 * plan derivation can target it without extra setup.
 */
function generateMainModule(projectName: string, moduleUlid: string): string {
  return `_ulid: ${moduleUlid}
slugs:
  - main
title: "${projectName} - Main Module"
type: module
status:
  maturity: draft
  implementation: not_started
description: |
  Default module for ${projectName}. Add your spec items here.

items: []
`;
}

/**
 * Default tasks file template
 */
function generateTasksFile(projectName: string): string {
  return `# ${projectName} - Tasks
# Track implementation work here

tasks: []
`;
}

/**
 * Prompt user for input
 */
async function prompt(question: string, defaultValue?: string): Promise<string> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  try {
    const suffix = defaultValue ? ` (${defaultValue})` : "";
    const answer = await rl.question(`${question}${suffix}: `);
    return answer.trim() || defaultValue || "";
  } finally {
    rl.close();
  }
}

/**
 * Derive project name from directory
 */
function deriveProjectName(targetDir: string): string {
  const dirName = path.basename(path.resolve(targetDir));
  // Convert kebab-case or snake_case to Title Case
  return dirName.replace(/[-_]/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

/**
 * Convert project name to slug (kebab-case)
 */
function toSlug(projectName: string): string {
  return projectName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

/**
 * Register the 'init' command
 * AC: @init-setup-integration ac-1 - shadow branch created and manifest exists
 * AC: @init-setup-integration ac-2 - core skills installed in .kspec/skills/
 * AC: @init-setup-integration ac-3 - rendered skill files, hooks, and kspec-agents.md present
 * AC: @init-setup-integration ac-4 - without --setup, behavior unchanged
 */
export function registerInitCommand(program: Command): void {
  program
    .command("init [directory]")
    .description("Initialize a new kspec project")
    .option("-n, --name <name>", "Project name")
    .option("--single-file", "Create manifest only (no modules directory)")
    .option("--no-prompt", "Skip interactive prompts, use defaults")
    .option("--force", "Overwrite existing files")
    .option("--no-shadow", "Skip shadow branch setup (create spec/ in main branch)")
    .option(
      "--setup",
      "Run full setup after initialization (install core skills, hooks, render skills, generate agents.md)",
    )
    .action(async (directory, options) => {
      try {
        const targetDir = directory || process.cwd();
        const useShadow = options.shadow !== false;

        // Determine project name
        let projectName = options.name;

        if (!projectName && options.prompt !== false) {
          const defaultName = deriveProjectName(targetDir);
          projectName = await prompt("Project name", defaultName);
        }

        if (!projectName) {
          projectName = deriveProjectName(targetDir);
        }

        // Shadow branch mode (default for git repos)
        if (useShadow) {
          // AC: @worktree-support ac-init-linked-wt-unchanged,
          //     ac-init-main-wt-unchanged, ac-init-guidance-direction,
          //     ac-init-guidance-path
          //
          // Resolve mainRoot and refuse to proceed when invoked from a
          // linked git worktree. The 2026-04-11 incident proved that a
          // lifecycle operation routed through a linked-worktree cwd
          // silently mutates the main working tree's shadow via git's
          // shared worktree admin (find_worktree_by_suffix). Hard-error
          // early with guidance pointing at the main working tree path.
          const projectRoots = resolveProjectRoots(targetDir);
          if (projectRoots?.isWorktree) {
            const { message, suggestion } = buildLinkedWorktreeMessage(
              "kspec init",
              projectRoots.mainRoot,
            );
            error(message);
            console.log(`  ${suggestion}`);
            process.exit(EXIT_CODES.ERROR);
          }

          const gitRoot = projectRoots?.mainRoot ?? getGitRoot(targetDir);

          if (!gitRoot) {
            if (await isGitRepo(targetDir)) {
              error(errors.git.couldNotDetermineRoot);
              process.exit(EXIT_CODES.ERROR);
            }
            // Not a git repo - fall back to non-shadow mode with warning
            warn("Not a git repository. Using non-shadow mode (spec/ in main branch).");
            await initNonShadow(targetDir, projectName, options);
            return;
          }

          // AC: @config-shadow — load project config for shadow settings
          const configResult = await loadProjectConfig(gitRoot);
          const config = configResult.config;

          // Emit warning if config had issues
          if (configResult.warning) {
            warn(configResult.warning);
          }

          // Determine shadow options from config
          const branchName = config.shadow.branch;
          const directoryName = config.shadow.directory;
          const shadowOptions = {
            branchName,
            directory: directoryName,
            remote: config.shadow.remote?.value,
            remoteType: config.shadow.remote?.type,
          };

          // AC: @config-shadow ac-9 — check for config mismatch
          const mismatch = await checkConfigMismatch(gitRoot, branchName, directoryName);
          if (mismatch.hasMismatch && !options.force) {
            warn("Shadow branch settings mismatch detected!");
            console.log("");
            console.log(mismatch.guidance);
            console.log("");
            console.log("Use --force to reinitialize with configured settings.");
            process.exit(EXIT_CODES.ERROR);
          }

          info(`Initializing kspec project: ${projectName}`);
          console.log(`  Mode: Shadow branch (${branchName} → ${directoryName}/)`);

          // Check if there's an existing manifest with session config
          // (e.g., when re-initializing with --force or after remote attach)
          let sessionsConfig: { storage?: string; branch?: string } | undefined;
          try {
            const { initContext } = await import("../../parser/index.js");
            const ctx = await initContext();
            if (ctx.manifest?.sessions?.storage === "branch") {
              sessionsConfig = ctx.manifest.sessions;
            }
          } catch (err) {
            // AC: @data-format-forward-compatibility ac-newer-version-refused
            // Re-initializing over an existing project whose manifest declares
            // a newer format must refuse before initializeShadow can touch it.
            const { isDeterministicFormatVersionIncompatibility } =
              await import("../../parser/index.js");
            if (isDeterministicFormatVersionIncompatibility(err)) {
              error(err.message, { code: err.code, suggestion: err.suggestion });
              process.exit(EXIT_CODES.ERROR);
            }
            // No existing manifest — session branch setup deferred to kspec setup
          }

          const result = await initializeShadow(gitRoot, {
            projectName,
            force: options.force,
            shadow: shadowOptions,
            sessions: sessionsConfig,
            worktreeRoot: config.dispatch.worktree_root,
          });

          if (!result.success) {
            error(errors.project.shadowInitFailed(result.error || "Unknown error"));
            process.exit(EXIT_CODES.ERROR);
          }

          if (result.alreadyExists) {
            info("Shadow branch already initialized");
          } else {
            if (result.createdFromRemote) {
              console.log(
                `  Attached to existing remote branch: ${shadowOptions.remote || "origin"}/${branchName}`,
              );
              console.log("  Remote tracking configured");
            } else if (result.branchCreated) {
              console.log(`  Created orphan branch: ${branchName}`);
              if (result.pushedToRemote) {
                console.log(
                  `  Pushed to remote: ${shadowOptions.remote || "origin"}/${branchName}`,
                );
              }
            }
            if (result.worktreeCreated) {
              console.log(`  Created worktree: ${directoryName}/`);
            }
            if (result.gitignoreUpdated) {
              console.log("  Updated .gitignore");
            }
            if (result.initialCommit) {
              console.log("  Created initial spec files");
            }
            if (result.sessionsDirectoryCreated) {
              console.log("  Created sessions directory: .kspec-sessions/");
            }
            if (result.sessionBranchCreated) {
              console.log("  Created session branch worktree: .kspec-sessions/");
            }
          }

          const _slug = toSlug(projectName);

          success(`Initialized kspec project in ${directoryName}/`, {
            projectName,
            mode: "shadow",
            branch: branchName,
          });

          // AC: @derivable-default-module — inform user about the default module
          console.log(
            `\n  Default module created: @main — use this ref when importing plans or adding specs`,
          );

          // AC: @init-setup-integration ac-2, ac-3 - Run full setup if --setup flag is passed
          if (options.setup) {
            console.log("\nRunning setup...\n");

            const setupResult = await runSetupPipeline(gitRoot, {
              dryRun: false,
              skipSkills: false,
              installHooks: true,
            });

            console.log();

            // AC: @scaffolded-project-config ac-file-valid-on-load — fail loudly on scaffold failure
            const scaffoldStep = setupResult.steps.find(
              (s) => s.name === "Scaffold project config",
            );
            if (scaffoldStep?.status === "failed") {
              warn(
                `Setup scaffold failed: ${scaffoldStep.message}. Fix the issue and re-run kspec setup.`,
              );
              process.exit(EXIT_CODES.ERROR);
            }

            if (setupResult.success) {
              success("Setup complete. Your project is ready for use.");
            } else {
              warn("Setup encountered issues. Run 'kspec setup --status' for details.");
            }
          } else {
            // AC: @init-setup-integration ac-4 - Without --setup, behavior unchanged
            console.log("\nNext steps:");
            console.log("  1. Run `kspec setup` for full agent integration");
            console.log("  2. Run `kspec help` to explore available commands");
            console.log(
              `\nNote: Spec files live in ${directoryName}/ (gitignored) and commit to ${branchName} branch`,
            );
          }
        } else {
          // Non-shadow mode (legacy)
          await initNonShadow(targetDir, projectName, options);
        }
      } catch (err) {
        error(errors.failures.initProject, err);
        process.exit(EXIT_CODES.ERROR);
      }
    });
}

/**
 * Initialize in non-shadow mode (spec/ in main branch)
 */
async function initNonShadow(
  targetDir: string,
  projectName: string,
  options: { force?: boolean; singleFile?: boolean },
): Promise<void> {
  const specDir = path.join(targetDir, "spec");

  // Check if spec already exists
  try {
    await fs.access(specDir);
    if (!options.force) {
      error(errors.conflict.specDirExists(targetDir));
      console.log("Use --force to overwrite existing files");
      process.exit(EXIT_CODES.CONFLICT);
    }
    warn("Overwriting existing spec files");
  } catch {
    // Directory doesn't exist, good to proceed
  }

  const singleFile = options.singleFile || false;
  const slug = toSlug(projectName);
  const defaultModuleUlid = singleFile ? undefined : ulid();

  info(`Initializing kspec project: ${projectName}`);
  console.log("  Mode: Non-shadow (spec/ in main branch)");

  // Create spec directory
  await fs.mkdir(specDir, { recursive: true });

  // Create manifest
  const manifestPath = path.join(specDir, `${slug}.yaml`);
  await fs.writeFile(
    manifestPath,
    generateManifest(projectName, singleFile, defaultModuleUlid),
    "utf-8",
  );
  console.log(`  Created ${path.relative(targetDir, manifestPath)}`);

  // Create tasks file
  const tasksPath = path.join(specDir, `${slug}.tasks.yaml`);
  await fs.writeFile(tasksPath, generateTasksFile(projectName), "utf-8");
  console.log(`  Created ${path.relative(targetDir, tasksPath)}`);

  if (!singleFile && defaultModuleUlid) {
    // Create modules directory and main module
    const modulesDir = path.join(specDir, "modules");
    await fs.mkdir(modulesDir, { recursive: true });

    const mainModulePath = path.join(modulesDir, "main.yaml");
    await fs.writeFile(mainModulePath, generateMainModule(projectName, defaultModuleUlid), "utf-8");
    console.log(`  Created ${path.relative(targetDir, mainModulePath)}`);
  }

  success(`Initialized kspec project in ${path.relative(process.cwd(), specDir) || "spec/"}`, {
    projectName,
    specDir,
    singleFile,
    mode: "non-shadow",
  });

  if (!singleFile) {
    // AC: @derivable-default-module — inform user about the default module
    console.log(
      `\n  Default module created: @main — use this ref when importing plans or adding specs`,
    );
  }

  console.log("\nNext steps:");
  console.log(`  1. Edit spec/${slug}.yaml to customize your project`);
  if (!singleFile) {
    console.log("  2. Add spec items to spec/modules/main.yaml");
  }
  console.log(`  ${singleFile ? "2" : "3"}. Run \`kspec tasks ready\` to see available tasks`);
}
